// components/Footer.vue
<template>
  <footer>
    <div class="layout-container">
      <div
        class="flex flex-col space-y-2 sm:justify-between items-start sm:items-center"
      >
        <div class="flex justify-start items-center space-x-4">
          <a
            href="https://github.com/shivaramakrishna99"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Icon
              name="mdi:github"
              size="24px"
              class="hover:text-slate-700 transform hover:scale-150 transition duration-300"
            />
          </a>
          <a
            href="https://www.linkedin.com/in/srks/"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Icon
              name="mdi:linkedin"
              size="24px"
              class="hover:text-slate-700 transform hover:scale-150 transition duration-300"
            />
          </a>
          <a
            href="https://x.com/srinivason99"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Icon
              name="mdi:twitter"
              size="24px"
              class="hover:text-slate-700 transform hover:scale-150 transition duration-300"
            />
          </a>
        </div>
        <p class="text-sm">
          <a href="mailto:shivaramakrishna.srinivasan@gmail.com">
            <code>shivaramakrishna.srinivasan@gmail.com</code>
          </a>
          |
          <a href="mailto:s5srinivasan@gmail.com">
            <code>s5srinivasan@gmail.com</code>
          </a>
        </p>
      </div>
    </div>
  </footer>
</template>

// app/components/footer.tsx
function ArrowIcon() {
  return (
    <svg
      width="12"
      height="12"
      viewBox="0 0 12 12"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M2.07102 11.3494L0.963068 10.2415L9.2017 1.98864H2.83807L2.85227 0.454545H11.8438V9.46023H10.2955L10.3097 3.09659L2.07102 11.3494Z"
        fill="currentColor"
      />
    </svg>
  )
}

export default function Footer() {
  return (
    <footer className="mb-16">
      <ul className="font-sm mt-8 flex flex-col space-x-0 space-y-2 text-neutral-600 md:flex-row md:space-x-4 md:space-y-0 dark:text-neutral-300">
        <li>
          <a
            className="flex items-center transition-all hover:text-neutral-800 dark:hover:text-neutral-100"
            rel="noopener noreferrer"
            target="_blank"
            href="https://github.com/"
          >
            <ArrowIcon />
            <p className="ml-2 h-7">github</p>
          </a>
        </li>
        <li>
          <a
            className="flex items-center transition-all hover:text-neutral-800 dark:hover:text-neutral-100"
            rel="noopener noreferrer"
            target="_blank"
            href="https://vercel.com/templates/next.js/portfolio-starter-kit"
          >
            <ArrowIcon />
            <p className="ml-2 h-7">view source</p>
          </a>
        </li>
      </ul>
      <p className="mt-8 text-neutral-600 dark:text-neutral-300">
        © {new Date().getFullYear()}
      </p>
    </footer>
  )
}
